export type { Color } from './colors'
export type { SpaceType } from './spacings'
export type { FontType } from './fonts'
export type { BreakpointType } from './breakpoints'
export { BREAKPOINTS } from './breakpoints'
